name: manta_dart
version: 0.0.3
description: Manta Protocol implementation for Dart
author: Appia Systems Limited
homepage: http://appia.co
documentation: https://appiapay.github.io/manta-python
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  mqtt_client: ^9.0.0
  decimal: ^1.0.0
  uuid: ^3.0.2
  json_annotation: '>=2.0.0'
  logging: ^1.0.0
  pointycastle: ^3.0.1
  rsa_pkcs:
    git: https://github.com/amaurel/rsa_pkcs.git
  async: ^2.0.1

dev_dependencies:
  test: ^1.3.4
  build_runner: ^1.0.0
  json_serializable: '>=2.0.0'
  mockito: ^3.0.0
